name: poem_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.3.2
  adaptive_theme: ^3.2.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_localizations: 
    sdk: flutter
  intl: any
  logger: ^1.3.0
  flutter_riverpod: ^2.3.4
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  firebase_ui_auth: ^1.2.1
  firebase_ui_oauth_google: ^1.1.1
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/backgrounds/
    - assets/appearance/align_icons/
  uses-material-design: true

