name: poems_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.3.2
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_localizations: 
    sdk: flutter
  intl: any
  logger: ^1.3.0
  flutter_riverpod: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  uses-material-design: true

